## DATA PARSING
[osclec_converter.singlephotons]
invert_polarity = false
threshold = 0
rawdata_directory = "raw_singlef"
output_file = "sp.root"

### PULSE ANALYSIS
[pulse_cfd_analysis.singlephotons]
cut_fraction = 0.35
threshold = 0
input_file = "sp.root"
output_file = "pulses.root"

### GET SPE SPECTRA HISTOGRAM
[get_hist.singlephotons]
branch_name = "energy"
bins = 80
x_low = 0
x_high = 0
input_file = "pulses.root"
output_file = "analysed.root"

### FIT SPE SPECTRA
[spe_fit.singlephotons]
hist_name = "energy"
n_smooth = 2
input_file = "analysed.root"
output_file = "analysed.root"
